using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BetterJump : MonoBehaviour
{
    /*
    public float fallMultiplier = 2.5f;
    public float lowJumpMultiplier = 2;
    Rigidbody2D theRB;

    private void Awake()
    {
        theRB = GetComponent<Rigidbody2D>();
    }


    // Update is called once per frame
    void Update()
    {
        if(theRB.velocity.y < 0)
        {
            theRB.velocity += Vector2.up * Physics2D.gravity.y * (fallMultiplier - 1) * Time.deltaTime;
        }else if (theRB.velocity.y > 0 && !Input.GetButton("Jump"))
        {
            theRB.velocity += Vector2.up * Physics2D.gravity.y * (lowJumpMultiplier - 1) * Time.deltaTime;
        }
    }*/
}
